export const ListElements = [
    {id: 1, value: "Элемент 1"},
    {id: 2, value: "Элемент 2"},
    {id: 3, value: "Элемент 3"},
    {id: 4, value: "Элемент 4"},
    {id: 5, value: "Элемент 5"},
    {id: 6, value: "Элемент 6"},
    {id: 7, value: "Элемент 7"},
    {id: 8, value: "Элемент 8"},
    {id: 9, value: "Элемент 9"},
    {id: 10, value: "Элемент 10"},
    {id: 11, value: "Элемент 11"},
    {id: 12, value: "Элемент 12"},
    {id: 13, value: "Элемент 13"},
    {id: 14, value: "Элемент 14"},
    {id: 15, value: "Элемент 15"},
    {id: 16, value: "Элемент 16"},
    {id: 17, value: "Элемент 17"}
]